Repository exercism/racket, pull requests merged in 2023-11, with the labels that each got.

#307 pop-count: update metadata
  config.json
  exercises/practice/pop-count/.meta/config.json
Labels: x:size/tiny

#309 Add charmparticle as contributor to sublist
  exercises/practice/sublist/.meta/config.json
Labels: x:rep/tiny

#312 CI: pin GitHub Actions runners
  .github/workflows/ci.yml
Labels: x:size/tiny

#315 CI: pin GitHub Actions workflows
  .github/workflows/ci.yml
Labels: x:size/tiny

#317 Update CI to use Racket 8.9 - 8.11
  .github/workflows/ci.yml
Labels: x:type/ci, x:size/tiny
