Repository exercism/racket, pull requests merged in 2024-02, with the labels that each got.

#348 `pop-count`: rename to `eliuds-eggs`
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/example.rkt
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/eliuds-eggs-test.rkt
  exercises/practice/eliuds-eggs/eliuds-eggs.rkt
Labels: x:size/tiny

#350 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#351 Bump CI to Racket 8.12
  .github/workflows/ci.yml
Labels: x:type/ci, x:rep/tiny

#352 Circular Buffer for racket
  config.json
  exercises/practice/circular-buffer/.docs/instructions.md
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/circular-buffer/.meta/example.rkt
  exercises/practice/circular-buffer/.meta/tests.toml
  exercises/practice/circular-buffer/circular-buffer-test.rkt
  exercises/practice/circular-buffer/circular-buffer.rkt
Labels: x:module/practice-exercise, x:rep/medium

#354 Spiral Matrix for Racket
  config.json
  exercises/practice/spiral-matrix/.docs/instructions.md
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/spiral-matrix/.meta/example.rkt
  exercises/practice/spiral-matrix/.meta/tests.toml
  exercises/practice/spiral-matrix/spiral-matrix-test.rkt
  exercises/practice/spiral-matrix/spiral-matrix.rkt
Labels: x:module/practice-exercise, x:rep/medium
