Repository exercism/racket, pull requests merged in 2024-04, with the labels that each got.

#369 Update binary search
  exercises/practice/binary-search/.docs/instructions.append.md
  exercises/practice/binary-search/binary-search-test.rkt
Labels: x:action/proofread, x:type/docs, x:rep/tiny

#370 zebra-puzzle: sync
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/tiny

#371 scrabble-score: sync
  exercises/practice/scrabble-score/.docs/instructions.md
  exercises/practice/scrabble-score/.docs/introduction.md
Labels: x:size/tiny

#374 all-your-base: sync
  exercises/practice/all-your-base/.docs/instructions.md
  exercises/practice/all-your-base/.docs/introduction.md
Labels: x:size/tiny

#373 dnd-character: sync
  exercises/practice/dnd-character/.docs/instructions.md
  exercises/practice/dnd-character/.docs/introduction.md
Labels: x:size/tiny

#375 zebra-puzzle: sync
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/tiny

#377 Sync docs and metadata
  exercises/practice/alphametics/.docs/instructions.md
  exercises/practice/alphametics/.meta/config.json
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.meta/config.json
  exercises/practice/matching-brackets/.docs/instructions.md
  exercises/practice/matching-brackets/.docs/introduction.md
  exercises/practice/meetup/.meta/config.json
  exercises/practice/parallel-letter-frequency/.docs/instructions.md
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/pig-latin/.docs/introduction.md
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/say/.docs/instructions.md
  exercises/practice/strain/.meta/config.json
  exercises/practice/two-bucket/.docs/instructions.md
Labels: x:action/sync, x:rep/tiny

#379 yacht: sync
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.docs/introduction.md
Labels: x:size/tiny
