Repository exercism/racket, pull requests merged in 2024-01, with the labels that each got.

#325 Minor typo fixes
  exercises/practice/bob/bob-test.rkt
  exercises/practice/robot-name/robot-name-test.rkt
Labels: x:action/proofread, x:rep/tiny

#322 Add pangram exercise
  config.json
  exercises/practice/pangram/.docs/instructions.md
  exercises/practice/pangram/.docs/introduction.md
  exercises/practice/pangram/.meta/config.json
  exercises/practice/pangram/.meta/example.rkt
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pangram/pangram-test.rkt
  exercises/practice/pangram/pangram.rkt
Labels: x:module/practice-exercise, x:rep/medium

#327 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny

#326 Update collatz-conjecture tests to allow use of contract
  exercises/practice/collatz-conjecture/.meta/example.rkt
  exercises/practice/collatz-conjecture/collatz-conjecture-test.rkt
Labels: x:module/practice-exercise, x:rep/small

#329 Sync docs and metadata
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
  exercises/practice/perfect-numbers/.docs/instructions.md
Labels: x:action/sync, x:rep/tiny

#331 Sync leap tests to problem-specifications
  exercises/practice/leap/leap-test.rkt
Labels: x:action/sync, x:rep/small

#328 Add square-root exercise
  config.json
  exercises/practice/square-root/.docs/instructions.md
  exercises/practice/square-root/.meta/config.json
  exercises/practice/square-root/.meta/example.rkt
  exercises/practice/square-root/.meta/tests.toml
  exercises/practice/square-root/square-root-test.rkt
  exercises/practice/square-root/square-root.rkt
Labels: x:module/practice-exercise, x:rep/medium

#332 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#330 Approaches for `leap`
  exercises/practice/leap/.approaches/boolean-chain/content.md
  exercises/practice/leap/.approaches/boolean-chain/snippet.txt
  exercises/practice/leap/.approaches/cond-form/content.md
  exercises/practice/leap/.approaches/cond-form/snippet.txt
  exercises/practice/leap/.approaches/config.json
  exercises/practice/leap/.approaches/introduction.md
  exercises/practice/leap/.approaches/pattern-matching/content.md
  exercises/practice/leap/.approaches/pattern-matching/snippet.txt
Labels: x:action/create, x:type/content

#333 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#334 Update broken cond approach link in introduction.md
  exercises/practice/leap/.approaches/introduction.md
Labels: x:rep/tiny

#338 Add sieve to racket
  config.json
  exercises/practice/sieve/.docs/instructions.md
  exercises/practice/sieve/.docs/introduction.md
  exercises/practice/sieve/.meta/config.json
  exercises/practice/sieve/.meta/example.rkt
  exercises/practice/sieve/.meta/tests.toml
  exercises/practice/sieve/sieve-test.rkt
  exercises/practice/sieve/sieve.rkt
Labels: x:rep/medium

#341 Add run-length encoding exercise
  config.json
  exercises/practice/run-length-encoding/.docs/instructions.md
  exercises/practice/run-length-encoding/.meta/config.json
  exercises/practice/run-length-encoding/.meta/example.rkt
  exercises/practice/run-length-encoding/.meta/tests.toml
  exercises/practice/run-length-encoding/run-length-encoding-test.rkt
  exercises/practice/run-length-encoding/run-length-encoding.rkt
Labels: x:module/practice-exercise, x:rep/medium

#342 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny

#343 Add knapsack exercise
  config.json
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.meta/config.json
  exercises/practice/knapsack/.meta/example.rkt
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/knapsack/knapsack-test.rkt
  exercises/practice/knapsack/knapsack.rkt
Labels: x:module/practice-exercise, x:rep/medium
