Repository exercism/racket, pull requests merged in 2024-05, with the labels that each got.

#381 Standardize difficulties and resort exercises
  config.json
Labels: x:rep/small

#382 spiral-matrix: sync
  exercises/practice/spiral-matrix/.docs/instructions.md
  exercises/practice/spiral-matrix/.docs/introduction.md
Labels: x:size/tiny

#385 kindergarten-garden: sync
  exercises/practice/kindergarten-garden/.docs/instructions.md
  exercises/practice/kindergarten-garden/.docs/introduction.md
Labels: x:size/tiny

#387 Add queen-attack
  config.json
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/queen-attack/.meta/config.json
  exercises/practice/queen-attack/.meta/example.rkt
  exercises/practice/queen-attack/.meta/tests.toml
  exercises/practice/queen-attack/queen-attack-test.rkt
  exercises/practice/queen-attack/queen-attack.rkt
Labels: x:module/practice-exercise, x:rep/large

#388 Bump CI to Racket 8.13
  .github/workflows/ci.yml
Labels: x:type/ci, x:rep/tiny

#389 bank-account: sync
  exercises/practice/bank-account/.docs/instructions.md
  exercises/practice/bank-account/.docs/introduction.md
Labels: x:size/tiny

#390 pig-latin: sync
  exercises/practice/pig-latin/.docs/instructions.md
Labels: x:size/tiny
